#!/usr/bin/with-contenv bash

# SUI
if [ ! -f /config/www/sui.lock ]; then
  echo "**** Installing SUI  ****"
  rm -f /config/www/*
  git clone \
    https://github.com/ThreadR-r/sui-dashboard-status.git \
      /config/www
  rm -f \
    /config/www/apps.json \
    /config/www/links.json
  rm -Rf /tmp/sui
  touch /config/www/sui.lock
else
  echo "**** SUI already installed, skipping  ****"
fi

# DCC
if [ ! -f /config/www/dcc.lock ] && [ $INSTALL_DCC = "true" ]; then
  echo "**** Installing DCC  ****"
  rm -Rf /config/www/dcc
  git clone -b \
    gh-pages \
      https://github.com/Griefed/dcc-web.git \
        /config/www/dcc
  rm -Rf /config/www/dcc/.git
  touch /config/www/dcc.lock
else
  echo "**** DCC already installed, skipping  ****"
fi

# NGINXConfig.io
if [ ! -f /config/www/nginxconfig.lock ] && [ $INSTALL_NGINXCONFIG_IO = "true" ]; then
  echo "**** Installing NGINXConfig.io  ****"
  rm -Rf /config/www/nginxconfig.io
  git clone -b \
    gh-pages \
      https://github.com/digitalocean/nginxconfig.io.git \
        /config/www/nginxconfig.io
  rm -Rf /config/www/nginxconfig.io/.git
  touch /config/www/nginxconfig.lock
else
  echo "**** NGINXConfig already installed, skipping  ****"
fi

# Triangulator
if [ ! -f /config/www/triangulator.lock ] && [ $INSTALL_TRIANGULATOR = "true" ]; then
  echo "**** Installing Triangulator  ****"
  rm -Rf /config/www/triangulator
  git clone \
    https://github.com/maeglin89273/triangulator.git \
      /config/www/triangulator
  rm -Rf /config/www/triangulator/.git
  touch /config/www/triangulator.lock
else
  echo "**** Triangulator already installed, skipping  ****"
fi

# Composerize
if [ ! -f /config/www/composerize.lock ] && [ $INSTALL_COMPOSERIZE = "true" ]; then
  echo "**** Installing Composerize  ****"
  rm -Rf /config/www/composerize
  mkdir -p /tmp/composerize
  mkdir -p /tmp/composerize-website
  mkdir -p /config/www/composerize
  git clone \
    https://github.com/magicmark/composerize.git \
      /tmp/composerize
  cp -r \
    /tmp/composerize/packages/composerize-website/. \
    /tmp/composerize-website
  cd /tmp/composerize-website
  sed -i \
    "s,https://www.composerize.com,$PROTOCOL://$DOMAIN/composerize,g" \
      /tmp/composerize-website/package.json
  npm install yarn@1.19.1 -g
  yarn add composerize
  make build
  cp -r \
    /tmp/composerize-website/build/. \
    /config/www/composerize/
  rm -Rf \
    /tmp/composerize \
    /tmp/composerize-website
  touch /config/www/composerize.lock
  cd /
else
  echo "**** Composerize already installed, skipping  ****"
fi

# Active GitHub Forks
if [ ! -f /config/www/active_github_forks.lock ] && [ $INSTALL_ACTIVE_GITHUB_FORKS = "true" ]; then
  echo "**** Installing Active GitHub Forks  ****"
  rm -Rf /config/www/active-github-forks
  git clone \
    https://github.com/lukaszmn/active-forks.git \
      /config/www/active-github-forks
  touch /config/www/active_github_forks.lock
  rm -Rf /config/www/active-github-forks/.git
else
  echo "**** Active GitHub Forks already installed, skipping  ****"
fi

# Permission Stuffs
chown -R \
  abc:abc \
    /config/www
