#!/usr/bin/with-contenv bash

# Default configs
if [ ! -f /config/www/apps.json ]; then
  cp -f \
    /defaults/apps.json \
    /config/www/apps.json
  sed -i \
    "s/DOMAIN/$DOMAIN/g" \
      /config/www/apps.json
  sed -i \
    "s/PROTOCOL/$PROTOCOL/g" \
      /config/www/apps.json
fi

if [ ! -f /config/www/links.json ]; then
  cp -f \
    /defaults/links.json \
    /config/www/links.json
fi

# Crontabs
mkdir -p \
  /config/crontabs
if [ ! -f /config/crintabs/root ]; then
  cp /etc/crontabs/root \
    /config/crontabs/
fi

# Permissions Stuffs
chown -R \
  abc:abc \
    /config/www
